// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "LoginRequest": {
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                },
                "required": [
                    "email",
                    "password"
                ],
                "type": "object"
            },
            "Problem": {
                "properties": {
                    "detail": {
                        "type": "string"
                    },
                    "status": {
                        "type": "integer"
                    },
                    "title": {
                        "type": "string"
                    }
                },
                "required": [
                    "status",
                    "title"
                ],
                "type": "object"
            },
            "Product": {
                "properties": {
                    "brand": {
                        "type": "string"
                    },
                    "category": {
                        "type": "string"
                    },
                    "id": {
                        "type": "integer"
                    },
                    "img": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "original_price_idr": {
                        "type": "integer"
                    },
                    "price_idr": {
                        "type": "integer"
                    },
                    "rating": {
                        "type": "number"
                    },
                    "rating_count": {
                        "type": "integer"
                    },
                    "slug": {
                        "type": "string"
                    },
                    "stock": {
                        "type": "integer"
                    },
                    "summary": {
                        "type": "string"
                    },
                    "tags": {
                        "items": {
                            "type": "string"
                        },
                        "type": "array",
                        "uniqueItems": false
                    }
                },
                "required": [
                    "brand",
                    "category",
                    "id",
                    "img",
                    "name",
                    "original_price_idr",
                    "price_idr",
                    "rating",
                    "rating_count",
                    "slug",
                    "stock",
                    "summary",
                    "tags"
                ],
                "type": "object"
            },
            "RegisterRequest": {
                "properties": {
                    "email": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "password": {
                        "minLength": 8,
                        "type": "string"
                    }
                },
                "required": [
                    "email",
                    "name",
                    "password"
                ],
                "type": "object"
            },
            "TokenResponse": {
                "properties": {
                    "token": {
                        "type": "string"
                    }
                },
                "required": [
                    "token"
                ],
                "type": "object"
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "scheme": "bearer",
                "type": "http"
            }
        }
    },
    "info": {
        "contact": {
            "email": "suhartanto@kekkon.nexus",
            "name": "Ryan Suhartanto",
            "url": "https://github.com/ryansuhartanto/koda-b8-backend"
        },
        "description": "{{escape .Description}}",
        "license": {
            "name": "MIT"
        },
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/auth/login": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/LoginRequest",
                                "summary": "body",
                                "description": "Credentials"
                            }
                        }
                    },
                    "description": "Credentials",
                    "required": true
                },
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/TokenResponse"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid body"
                    },
                    "401": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid credentials"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "Exchange credentials for a token",
                "tags": [
                    "auth"
                ]
            }
        },
        "/auth/register": {
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/RegisterRequest",
                                "summary": "body",
                                "description": "Credentials"
                            }
                        }
                    },
                    "description": "Credentials",
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/TokenResponse"
                                }
                            }
                        },
                        "description": "Created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid body"
                    },
                    "409": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Email already registered"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "Register an account",
                "tags": [
                    "auth"
                ]
            }
        },
        "/healthz": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {
                                        "type": "string"
                                    },
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "503": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Database unreachable"
                    }
                },
                "summary": "Liveness and database reachability",
                "tags": [
                    "meta"
                ]
            }
        },
        "/products": {
            "get": {
                "parameters": [
                    {
                        "description": "Match against the product name",
                        "in": "query",
                        "name": "search",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Category name",
                        "in": "query",
                        "name": "category",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "One of baru, unggulan, promo",
                        "in": "query",
                        "name": "tag",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "One of newest, price_asc, price_desc, rating",
                        "in": "query",
                        "name": "sort",
                        "schema": {
                            "enum": [
                                "newest",
                                "price_asc",
                                "price_desc",
                                "rating"
                            ],
                            "type": "string"
                        }
                    },
                    {
                        "description": "Rows to return, 1 to 100",
                        "in": "query",
                        "name": "limit",
                        "schema": {
                            "default": 20,
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Rows to skip",
                        "in": "query",
                        "name": "offset",
                        "schema": {
                            "default": 0,
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "items": {
                                        "$ref": "#/components/schemas/Product"
                                    },
                                    "type": "array"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Invalid query"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "List products",
                "tags": [
                    "products"
                ]
            }
        },
        "/products/{slug}": {
            "get": {
                "parameters": [
                    {
                        "description": "Product slug",
                        "in": "path",
                        "name": "slug",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Product"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "No such product"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Internal error"
                    }
                },
                "summary": "Fetch one product by slug",
                "tags": [
                    "products"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "http://localhost:3001"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "BeliMudah API",
	Description:      "E-commerce API for the BeliMudah storefront.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
