// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "schemas": {
            "Problem": {
                "properties": {
                    "detail": {
                        "type": "string"
                    },
                    "status": {
                        "type": "integer"
                    },
                    "title": {
                        "type": "string"
                    }
                },
                "required": [
                    "status",
                    "title"
                ],
                "type": "object"
            }
        },
        "securitySchemes": {
            "BearerAuth": {
                "scheme": "bearer",
                "type": "http"
            }
        }
    },
    "info": {
        "contact": {
            "email": "suhartanto@kekkon.nexus",
            "name": "Ryan Suhartanto",
            "url": "https://github.com/ryansuhartanto/koda-b8-backend"
        },
        "description": "{{escape .Description}}",
        "license": {
            "name": "MIT"
        },
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "",
        "url": ""
    },
    "paths": {
        "/healthz": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "additionalProperties": {
                                        "type": "string"
                                    },
                                    "type": "object"
                                }
                            }
                        },
                        "description": "OK"
                    },
                    "503": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Problem"
                                }
                            }
                        },
                        "description": "Database unreachable"
                    }
                },
                "summary": "Liveness and database reachability",
                "tags": [
                    "meta"
                ]
            }
        }
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "http://localhost:3001"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "BeliMudah API",
	Description:      "E-commerce API for the BeliMudah storefront.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
